// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

export function sumOfEvenValuedTerms(n) {
  let previousPreviousTerm = 1;
  let previousTerm = 1;
  let currentTerm = 0;
  let sum = 0;
  while (currentTerm < n) {
    console.log(currentTerm);
    if (currentTerm % 2 == 0) {
      sum = sum + currentTerm;
    }

    currentTerm = previousPreviousTerm + previousTerm;
    previousPreviousTerm = previousTerm;
    previousTerm = currentTerm;
  }
  return sum;
}

const exampleInput = 100;
const exampleOutput = 44;

const exampleResult = sumOfEvenValuedTerms(exampleInput);
if (exampleOutput == exampleResult) {
  const realInput = 4_000_000;
  const realResult = sumOfEvenValuedTerms(realInput);
  console.log("YAY! You go girl!");
  console.log("Real result is:", realResult);
} else {
  console.log("You are almost there!");
  console.log("Your example result is:", exampleResult);
}
